#!/usr/bin/env php
<?php

// Autoload file from composer
require __DIR__ . '/vendor/autoload.php';

use app\Core\Cream;
use app\Core\Console\ServeCommand;
use app\Core\Console\MakeControllerCommand;
use app\Core\Console\MakeViewCommand;
use app\Core\Console\MakeModelCommand;

$cream = new Cream();

$cream->registerCommand(new ServeCommand());
$cream->registerCommand(new MakeControllerCommand());
$cream->registerCommand(new MakeViewCommand());
$cream->registerCommand(new MakeModelCommand());

$cream->run();
